version: '3.7'
services:
  mariadb:
    image: mysql
    restart: always
    networks: 
      - fsDB
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./data:/var/run/mysql
  node:
    image: "node:18"
    user: "node"
    working_dir: /home/node/app
    networks:
      - fsDB
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/home/node/app
    ports:
      - "4000:4000"
    # command: "npm install & npm run watch"
    command: >
      sh -c "rm -rf node_modules &&
             npm install &&
             npm run watch"
    restart: always
    stdin_open: true
    tty: true
    depends_on:
      - mariadb
networks:
  fsDB:
